# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hansode/centos-6.5-x86_64"

  config.vm.synced_folder ".", "/vagrant" #, type: "nfs"
  config.vm.synced_folder "/tmp/nexus-2.1.2/sonatype-work", "/opt/sonatype-work.old"  #, type: "nfs"
 
  config.vm.hostname = "nexus.vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--name", "nexus.vagrant", "--memory", "1024", "--cpus", "1", "--ioapic", "on"]
  end
  config.vm.network "private_network", ip: "192.168.33.110"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    #ansible.inventory_path = "provisioning/ansible/inventories/vagrant_servers"
    ansible.verbose = "v"
    ansible.limit = 'all'
  end
end